name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/bence-banyai/html-13a-a:01
        docker login ghcr.io -u bence-banyai -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/bence-banyai/html-13a-a:01
